<a href="https://colab.research.google.com/github/minotajordan/metaheuristic/blob/main/Hill_climbing_nD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Define the function to be minimized (sphere function)
def sphere(pos):
  return (pos * pos).sum()

In [ ]:
# Define the hill_climbing algorithm
def hill_climbing(start_pos, learning_rate, num_iterations):
    # Initialize the parameters
    d = len (start_pos)
    pos = start_pos
    fpos = sphere(pos)
    history = []
    history.append((pos, fpos))

    # Perform the hill_climbing iterations
    for i in range(num_iterations):
        # Update the parameters
        rnd = np.random.uniform(low=-learning_rate, high=learning_rate, size=(d,))
        pos2 = pos + rnd
        fpos2 = sphere(pos2)

        if fpos2 < fpos:
          pos = pos2
          fpos = fpos2

        # Save the history of the parameters
        history.append((pos, fpos))

    return pos, fpos, history

In [ ]:
# Perform hill climbing
d=10
learning_rate = 0.2
num_iterations = 20

np.random.seed (5)
start_pos = np.random.uniform(low=-10, high=10, size=(d,))

best_pos, f_best, history = hill_climbing(start_pos, learning_rate, num_iterations)

# List the history points
for point in history:
  print(point)

(array([-5.56013658,  7.41464612, -5.86561689,  8.37221816, -0.23177622,
        2.23487726,  5.31815713,  0.36835976, -4.06398997, -6.24557543]), 279.38170195963085)
(array([-5.72784007,  7.51002224, -5.8890932 ,  8.23554211, -0.07980141,
        2.14451184,  5.28385114,  0.28679173, -4.0124748 , -6.2136403 ]), 279.03007001250296)
(array([-5.68786839,  7.41634989, -5.97521885,  8.13697739, -0.14877583,
        2.00217756,  5.15009628,  0.47236394, -3.82838412, -6.33827444]), 274.87545035531116)
(array([-5.87814577,  7.29817211, -5.89528141,  8.24878322, -0.3396026 ,
        2.03324271,  4.95075315,  0.47855299, -3.77246605, -6.14402468]), 271.5815961759703)
(array([-5.87814577,  7.29817211, -5.89528141,  8.24878322, -0.3396026 ,
        2.03324271,  4.95075315,  0.47855299, -3.77246605, -6.14402468]), 271.5815961759703)
(array([-5.76980413,  7.29214454, -6.08363678,  8.0833935 , -0.49502107,
        1.93374075,  5.13671927,  0.53125941, -3.64580197, -6.11759188]), 270.1872215571193)
(